name: "Build and deploy Marathon"

on:
  push:
    branches: [main]
    paths:
      - 'gamesdk/**'
      - 'core/**'
      - '.github/workflows/build-marathon.yaml'
      - 'marathon/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          gradle-command: "gradle marathon:build --no-daemon"
          dockerfile-path: './marathon/Dockerfile'
          dockerfile-context: './marathon/'

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "marathon"
          values-path: "server/values/marathon.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
