name: "Build and deploy BlockSumo"

on:
  push:
    branches: [main]
    paths:
      - 'gamesdk/**'
      - 'core/**'
      - '.github/workflows/build-blocksumo.yaml'
      - 'blocksumo/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          project: "blocksumo"
          gradle-command: "gradle blocksumo:build --no-daemon"
          dockerfile-path: './blocksumo/Dockerfile'
          dockerfile-context: './blocksumo/'

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "blocksumo"
          values-path: "server/values/blocksumo.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
