name: "Build and deploy Minesweeper"

on:
  push:
    branches: [main]
    paths:
      - 'gamesdk/**'
      - 'core/**'
      - '.github/workflows/build-minesweeper.yaml'
      - 'minesweeper/**'
      - 'build.gradle.kts'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          project: "minesweeper"
          gradle-command: "gradle minesweeper:build --no-daemon"
          dockerfile-path: './minesweeper/Dockerfile'
          dockerfile-context: './minesweeper/'

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "minesweeper"
          values-path: "server/values/minesweeper.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
